const CONSTANTS = {
  ALL_WORDS: 'allWords',
  ANTONYM: 'antonym',
  ANTONYMS: 'Antonyms',
  APP_TITLE: 'Shabadavali.',
  BACK: 'Back',
  DASHBOARD: 'Dashboard',
  DESCRIPTION: 'Made by Khalis Foundation',
  ENTER_DETAILS: 'Please enter your details',
  EXAMPLES: 'Examples',
  GURMUKHI: 'gurmukhi',
  GURFATEH_PUNJABI: 'ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ ॥ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਿਹ ॥',
  KNOW_MORE: 'Know More',
  LOADING: 'Loading...',
  LOGIN_INFO: `Before you start adding new words to your 
    vocabulary, we just need some information from you.`,
  NUM_COINS: 13,
  OR: 'or',
  PROFILE: 'Profile',
  QUESTIONS: 'Questions',
  QUESTIONS_TO_GO: 'QUESTIONS TO GO TO YOUR NEXT NANAK COIN!!',
  SETTINGS: 'Settings',
  SIGN_IN: 'Sign In',
  SIGN_IN_WITH_GOOGLE: 'Sign In with Google',
  SIGN_OUT: 'Sign Out',
  SIGN_UP: 'Sign Up',
  SHASHA: 'ਸ਼',
  SYNONYM: 'synonym',
  SYNONYMS: 'Synonyms',
  TITLE: 'Shabadavali',
  TOTAL_NUM_QUESTIONS: 13,
  WELCOME: 'Welcome',
  WORD_NOT_FOUND: 'Word not found',
};

export default CONSTANTS;
